CREATE DATABASE IF NOT EXISTS EUROPA_REPORT;
USE EUROPA_REPORT;

CREATE TABLE info IF NOT EXISTS (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	date DATE NOT NULL,
	subscribers BIGINT NOT NULL,
	active_subscribers BIGINT NOT NULL,
	submission BIGINT DEFAULT NULL,
	comments BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE lookup IF NOT EXISTS (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	abbreviation VARCHAR(45) NOT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=latin1;